version: "3.9"
services:
  jenkins-docker:
    image: docker:dind
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
      - DOCKER_TLS_CERTDIR=/certs
    ports:
      - "2376:2376"
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    networks:
      - jenkins
  jenkins-blueocean:
    build: ./jenkins-blueocean/
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-docker-certs:/certs/client:ro
      - jenkins-data:/var/jenkins_home
    networks:
      - jenkins
    depends_on:
      - jenkins-docker
networks:
  jenkins:
volumes:
  jenkins-docker-certs:
  jenkins-data: